Repository opentargets/data_pipeline, pull requests merged in 2018-10, with the labels that each got.

#327 remove old mouse model evidence generation
  mrtarget/CommandLine.py
  mrtarget/modules/MouseModels.py
Labels: Kind: Maintenance, Priority: Low

#326 Stop repeated logging for HPA missing tissues
  mrtarget/modules/HPA.py
Labels: Kind: Enhancement, Priority: Low

#328 remove lingering action objects
  .circleci/config.yml
  mrtarget/common/__init__.py
  mrtarget/modules/EvidenceString.py
Labels: Kind: Maintenance, Priority: Low

#333 Change MySQL port to 3306 (standard)
  mrtarget/modules/Ensembl.py
Labels: Kind: Maintenance, Priority: Low

#331 changes to allow restoration from remote urls
  docker-compose.yml
Labels: Kind: Enhancement, Priority: Low

#339 pin EFO version
  mrtarget/resources/ontology_config.ini
Labels: Kind: Maintenance, Priority: High

#338 Af requirements cleanup
  mrtarget/modules/Ontology.py
  requirements.txt
Labels: Kind: Maintenance, Priority: Low

#335 include tractability data
  mrtarget/common/safercast.py
  mrtarget/modules/Association.py
  mrtarget/plugins/gene/tractability.py
  tests/test_common_safercast.py
Labels: Kind: New feature, Priority: High, Status: In progress

#337 Don't create log file if --log-http is not specified
  mrtarget/CommandLine.py
Labels: Kind: Bug, Priority: Low

#341 move to travis, push to quay and use make instead the former docker entry point
  .circleci/config.yml
  .circleci/images/primary/Dockerfile
  .circleci/images/primary/README.md
  .circleci/images/primary/requirements.txt
  .travis.yml
  Dockerfile
  Makefile
  README.md
  mrtarget/CommandLine.py
  mrtarget/Settings.py
  mrtarget/modules/Dump.py
  mrtarget/modules/Ontology.py
  nose.cfg
  requirements.txt
Labels: Kind: Enhancement, Kind: Maintenance, Kind: New feature, Priority: High

#342 expanded logging
  mrtarget/modules/EFO.py
  mrtarget/modules/Ensembl.py
  mrtarget/modules/HPA.py
  mrtarget/modules/MP.py
  mrtarget/modules/Reactome.py
  mrtarget/modules/Uniprot.py
Labels: Kind: Enhancement, Priority: High

#343 make uniprot works again
  mrtarget/CommandLine.py
  mrtarget/Settings.py
  mrtarget/modules/Uniprot.py
  requirements.txt
  tests/resources/uniprot.xml.gz
  tests/test_uniprot.py
Labels: Kind: Bug, Status: Fixed, priority/critical-urgent

#344 Af docker improvements
  .dockerignore
  Dockerfile
  broken_tests/__init__.py
  broken_tests/resources/genes_with_non_reference_ensembl_ids.tsv
  broken_tests/resources/intogen_opentargets.tsv
  broken_tests/resources/test-medlinexml/test_baseline.xml.gz
  broken_tests/resources/test-medlinexml/test_update.xml.gz
  broken_tests/resources/test-spacy/disease.xml
  broken_tests/resources/test-spacy/geneProt.xml
  broken_tests/resources/test_abstract_nlp.txt
  broken_tests/resources/test_genes.json
  broken_tests/resources/test_ortholog.txt
  broken_tests/test_GE.py
  broken_tests/test_chembl.py
  broken_tests/test_drug_search.py
  broken_tests/test_eco.py
  broken_tests/test_efo.py
  broken_tests/test_evidencevalidation.py
  broken_tests/test_literature.py
  broken_tests/test_literature_nlp.py
  broken_tests/test_literature_nlp_bioentities.py
  broken_tests/test_literature_qc.py
  broken_tests/test_ontology.py
  requirements.txt
Labels: Kind: Maintenance, Priority: Medium

#345 feat: tag quay to lastest when the branch is master
  .travis.yml
  Dockerfile
Labels: Kind: Enhancement, Kind: Maintenance, Priority: Low

#348 fix efo logging
  mrtarget/modules/EFO.py
Labels: Kind: Maintenance, Priority: Critical

#350 Af reactome fix
  mrtarget/modules/Reactome.py
Labels: Kind: Maintenance, Priority: Critical
