Repository opentargets/data_pipeline, pull requests merged in 2018-11, with the labels that each got.

#352 remove unused file
  mrtarget/common/OBOSimpleParser.py
Labels: Kind: Maintenance, Priority: Low

#351 Af make in docker
  .dockerignore
  .gitignore
  Dockerfile
  Makefile
  README.md
  docker-compose.yml
  mrtarget/CommandLine.py
  mrtarget/Settings.py
  mrtarget/common/__init__.py
  mrtarget/modules/EvidenceValidation.py
  mrtarget/modules/QC.py
  requirements.txt
Labels: Kind: Enhancement, Priority: Medium

#359 Remove legacy references to $(VALIDATE_CMD)
  Makefile
Labels: Kind: Maintenance, Priority: Low

#362 Af 18.10.2 backport
  Makefile
  README.md
  mrtarget/modules/ChEMBL.py
  mrtarget/resources/evidences_sources.txt
  requirements.txt
  scripts/generate_minimal_dataset.sh
  scripts/run_minimal_data_pipeline.sh
  scripts/run_on_gcp.sh
  scripts/uris_1704.txt
Labels: Kind: Maintenance, Priority: High

#369 Fix mis-spelled .PHONY target (was .PHONEY) in Reactome step
  Makefile
Labels: Kind: Bug, Priority: High

#368 refactor: improve chembl plugin when downloading making it more resil…
  mrtarget/common/LookupHelpers.py
  mrtarget/modules/ChEMBL.py
  requirements.txt
  tests/__init__.py
  tests/test_chembl.py
Labels: Kind: Enhancement, Kind: Maintenance, Priority: Low

#371 Ensembl refactor
  Makefile
  mrtarget/CommandLine.py
  mrtarget/Settings.py
  mrtarget/common/ElasticsearchLoader.py
  mrtarget/modules/Ensembl.py
Labels: Kind: Enhancement, Priority: Medium
