Repository opentargets/data_pipeline, pull requests merged in 2019-01, with the labels that each got.

#412 url does not exist
  mrtarget/common/IO.py
  mrtarget/common/__init__.py
  mrtarget/modules/Evidences.py
  tests/test_common_io.py
Labels: Kind: Bug, Priority: Medium

#425 Af 382 drug search missing
  mrtarget/common/ElasticsearchQuery.py
  mrtarget/modules/ChEMBL.py
Labels: Kind: Bug

#437 Af efo 2.104
  mrtarget/resources/ontology_config.ini
Labels: Kind: Maintenance
